version: '2'

services:
  web:
    build: ./docker/wordpress
    image: my-wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      DB_HOST: mysql
      USER_ID: ${USER_ID}
    links:
      - mysql:mysql
    volumes:
      - ./mysql:/mysql
      - ./wordpress/html:/var/www/html
      - ./wordpress/conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
